import { BarChart3, Download, ScanLine, UserRound } from 'lucide-react'
import type { BehaviorEvent, ClassroomReport } from '../types'
import { downloadJson, formatTime, normalRatio } from '../platform'
import { Badge, EmptyState, Metric, Panel } from './ui'

export function ReportView({ report }: { report: ClassroomReport }) {
  return <><section className="report-summary"><span className="summary-icon"><ScanLine size={24} /></span><div><span className="eyebrow">CLASSROOM REVIEW</span><h2>课堂整体总结</h2><p>{report.classroom_summary || '根据本次课堂记录生成逐人统计。'}</p></div><button className="button" onClick={() => downloadJson('课堂行为报告.json', report)}><Download size={15} />导出报告</button></section><div className="section-caption"><h2>逐人行为记录</h2><span>{report.students.length} 位已识别学生 · 座位标签</span></div><div className="student-report-grid">{report.students.map(s => <article className="panel student-report" key={s.student_id}><header><span className="student-avatar"><UserRound size={22} /></span><h3>{s.label}</h3><Badge tone={s.reminder_count ? 'warning' : 'success'}>{s.reminder_count ? `${s.reminder_count} 次异常记录` : '正常状态'}</Badge></header><div className="behavior-tags">{Object.entries(s.behaviors).map(([name, stat]) => <div key={name}><span>{name}</span><strong>{stat.count} 次</strong><small>约 {Math.round(stat.duration)} 秒</small></div>)}</div><p className="student-summary">{s.summary}</p><details><summary>查看行为时间轴（{s.timeline.length} 条）</summary><ul className="report-timeline">{s.timeline.map(t => <li key={t.event_id}><time>{formatTime(t.time)}</time><span>{t.behavior}</span><Badge tone={t.severity === 'info' ? 'success' : 'warning'}>{t.severity === 'info' ? '正常' : '关注'}</Badge></li>)}</ul></details></article>)}</div>{!report.students.length && <EmptyState title="本次没有识别到可统计的学生" text="请确认学生处于画面内、光线充足，并等待至少一次分析完成。" />}</>
}

export function Analysis({ events, report, loading, samples, goLive }: { events: BehaviorEvent[]; report: ClassroomReport | null; loading: boolean; samples: number; goLive: () => void }) {
  const ratio = normalRatio(events)
  const grouped = Object.entries(events.reduce<Record<string, number>>((all, e) => { all[e.behavior] = (all[e.behavior] ?? 0) + 1; return all }, {})).sort((a, b) => b[1] - a[1])
  return <><div className="metrics-grid three"><Metric label="分析画面" value={samples} unit="次" note="当前课堂累计分析次数" icon={ScanLine} /><Metric label="正常记录占比" value={ratio === null ? '—' : ratio} unit={ratio === null ? '' : '%'} note="正常事件数 / 全部事件数" accent="mint" /><Metric label="已识别学生" value={new Set(events.flatMap(e => e.students.map(s => s.id))).size} unit="人" note="根据座位位置匹配，非身份识别" icon={UserRound} /></div><Panel title="行为分布" subtitle="当前课堂 · 按事件条数统计" action={<Badge>实时更新</Badge>}>{grouped.length ? <div className="horizontal-chart">{grouped.map(([name, count]) => <div key={name}><span title={name}>{name}</span><div><i style={{ width: `${count / events.length * 100}%` }} /></div><strong>{count} 次</strong></div>)}</div> : <EmptyState title="课堂分析从真实观察开始" text="开启摄像头后，将展示学生状态与行为分布；结束观察后生成完整报告。" action={<button className="button primary" onClick={goLive}>前往实时课堂</button>} />}</Panel><div className="analysis-disclaimer"><BarChart3 size={18} /><p>当前统计反映已识别事件的分布，不构成教学质量或学生专注度评分。教师行为评价尚未接入。</p></div>{loading ? <div className="panel loading-panel" role="status">正在汇总课堂记录并生成报告…</div> : report ? <ReportView report={report} /> : <div className="report-pending"><ScanLine size={20} /><div><strong>课堂报告将在观察结束后生成</strong><p>包含课堂总结、逐人行为统计和事件时间轴。</p></div></div>}</>
}
