import { Building2, Check, RefreshCw, Save } from 'lucide-react'
import { useState } from 'react'
import type { WorkspaceSettings } from '../platform'
import { Badge, Panel } from './ui'
export type ServiceStatus = 'loading' | 'online' | 'offline'

export function SettingsPage({ settings, save, status, refresh }: { settings: WorkspaceSettings; save: (s: WorkspaceSettings) => boolean; status: ServiceStatus; refresh: () => void }) {
  const [draft, setDraft] = useState(settings)
  const [saved, setSaved] = useState(false)
  return <div className="settings-grid"><Panel title="学校与课堂信息" subtitle="用于本机工作区展示和课堂报告归档" action={<Building2 size={20} />}><form className="settings-form" onSubmit={e => { e.preventDefault(); setSaved(save(Object.fromEntries(Object.entries(draft).map(([k, v]) => [k, v.trim()])) as unknown as WorkspaceSettings)) }}>{([['school', '学校 / 机构名称', '例如：实验中学'], ['classroom', '教学楼 / 教室', '例如：教学楼 A · 301'], ['course', '课程名称', '例如：七年级语文'], ['observer', '课堂观察员', '例如：教学督导']] as const).map(([key, label, placeholder]) => <label key={key}>{label}<input required maxLength={60} value={draft[key]} placeholder={placeholder} onChange={e => { setSaved(false); setDraft({ ...draft, [key]: e.target.value }) }} /></label>)}<p className="muted">信息仅保存在当前浏览器；修改后应用于下一次课堂观察。这里的观察员名称不代表登录账户或授权角色。</p><button className="button primary" type="submit">{saved ? <Check size={16} /> : <Save size={16} />}{saved ? '已保存' : '保存工作区信息'}</button></form></Panel><div className="settings-aside"><Panel title="服务连接" action={<Badge tone={status === 'online' ? 'success' : status === 'offline' ? 'warning' : 'neutral'}>{status === 'online' ? '已连接' : status === 'offline' ? '暂不可用' : '连接中'}</Badge>}><div className="service-details"><div><span>课堂分析服务</span><strong>{status === 'online' ? '已响应' : '等待响应'}</strong></div><div><span>课堂接入方式</span><strong>浏览器摄像头</strong></div><div><span>异常提醒</span><strong>中文语音 + 文字</strong></div><div><span>历史报告</span><strong>本机浏览器保存</strong></div><button className="button full-width" disabled={status === 'loading'} onClick={refresh}><RefreshCw size={15} className={status === 'loading' ? 'spin' : ''} />重新检查连接</button><p>首次连接免费云服务可能需要等待唤醒，请稍候重试。</p></div></Panel><Panel title="开始前，你需要知道"><ol className="help-steps"><li><strong>允许访问摄像头</strong><p>手机优先后置，电脑自动选择可用摄像头。</p></li><li><strong>确认语音可以播放</strong><p>上传照片后先测试语音，调高媒体音量；保持页面在前台。</p></li><li><strong>固定画面，获得更稳定的观察</strong><p>让学生上半身与桌面清晰可见，避免逆光与频繁切换镜头。</p></li><li><strong>结束后查看报告</strong><p>正常行为仅记录，异常行为触发提醒。报告用于辅助复盘。</p></li></ol></Panel></div></div>
}
